name: CI
on: [push, pull_request]

env:
  MONGODB_URI: ${{ env.TEST_MONGODB_URI }}
  JWT_SECRET: ${{ env.TEST_JWT_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.2.0
    - name: Create .env file
      run: |
        echo "MONGODB_URI=${{ env.TEST_MONGODB_URI }}" >> .env
        echo "JWT_SECRET=${{ env.TEST_JWT_SECRET }}" >> .env
    - name: Install dependencies
      run: |
        cd auth
        npm ci
        cd ..
        npm ci
    - name: Run tests
      run: |
        npm test
