name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.2.0
    - name: Install dependencies
      run: |
        cd auth
        npm ci
        cd ..
        npm ci
    - name: Run tests
      run: |
        cd auth
        npm test -- --exit
        cd ..
        npm test -- --exit
