name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.2.0
    - name: Create .env file
      run: |
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
    - name: Install dependencies
      run: |
        cd auth
        npm ci
        cd ..
        npm ci
    - name: Run tests
      run: |
        cd auth
        npm test -- --exit
        cd ..
        npm test -- --exit
